### ISSUE TITLE
Error: Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by Benoit1980** [npm/wrappy#6]
Hello,

I am really struggling with this one, I emailed the community at npm, but no reply.
When installing Node.js on windows 10 pro 64 bit and type npm -v in the command I get the below error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Benny\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Any idea why please? Noone has been able to help me at the moment.

I uninstalled, reinstalled Node.js, tried really everything I could, same error again and again.

Thank you!

**Comment by zhangtianyou** [comment]
现在解决了吗
